[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd frontends && npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step required for static frontend'"]

[start]
cmd = "cd frontends && npm start"

[variables]
NODE_ENV = "production"
