[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm -r --filter='@autorestock/*' build", "pnpm build"]

[start]
cmd = "pnpm start"
